### ISSUE TITLE
expected return type is "Array[Vector2]"

### ISSUE THREAD

**Issue by Nauja** [d-bucur/godot-vision-cone#3]
Hello, I just installed this plugin in Godot 4, and when testing I got the error `expected return type is "Array[Vector2]"` in `calculate_vision_shape`.

I believe
`var new_vision_points = []`
should be changed to:
`var new_vision_points: Array[Vector2] = []`

**Comment by ivan-resetnikov** [comment]
I fixed it removing sub-type from the var intialization string:
`var new_vision_points: Array`

May be not the best way to fix it, but it works for me

**Comment by StukaJU87** [comment]
`var new_vision_points: Array[Vector2] = []`

Can confirm this solves the problem, plugin seems to be working as expected.

**Comment by d-bucur** [comment]
This seems to have changed between the beta and final release of Godot4. I've updated it in bd0312a. Thanks for the report!
