### ISSUE TITLE
Example scene broken in current Godot 4 version

### ISSUE THREAD

**Issue by TicklesTheBrain** [d-bucur/godot-vision-cone#4]
Seems to be broken in current Godot 4.0.2. Screenshot from example: 

![image](https://github.com/d-bucur/godot-vision-cone/assets/21967696/32529052-3fca-4830-9cdd-e82a79328401)

**Comment by d-bucur** [comment]
Just tested this with 4.0.3 and bd0312a32efcdf5ad777b4ee51f8f7944b8d81b5 and the example scene works fine. Collision masks are properly set. Probably some error with the editor
